# Generated by Django 4.2.7 on 2026-02-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
