# Generated by Django 4.2.11 on 2026-02-16 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_delete_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminatedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_student_id', models.CharField(help_text='Original student ID', max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('personal_email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=50)),
                ('program', models.CharField(choices=[('MCA', 'Master of Computer Applications'), ('MScIT', 'Master of Science in Information Technology'), ('BCA', 'Bachelor of Computer Applications'), ('PGDCA', 'Post Graduate Diploma in Computer Applications')], max_length=10)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')])),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_relation', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=50)),
                ('admission_year', models.IntegerField()),
                ('termination_reason', models.TextField(help_text='Reason for student termination/deletion')),
                ('termination_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(help_text='Original student creation date')),
                ('updated_at', models.DateTimeField(help_text='Original student last update date')),
                ('is_restored', models.BooleanField(default=False, help_text='Whether this student has been restored')),
                ('restored_date', models.DateTimeField(blank=True, help_text='Date when student was restored', null=True)),
                ('restored_by', models.ForeignKey(blank=True, help_text='Admin who restored the student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_students', to=settings.AUTH_USER_MODEL)),
                ('terminated_by', models.ForeignKey(help_text='Admin who terminated the student', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terminated Student',
                'verbose_name_plural': 'Terminated Students',
                'ordering': ['-termination_date'],
            },
        ),
    ]
