# Generated by Django 4.2.7 on 2026-02-21 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_type', models.CharField(choices=[('total_vehicles', 'Total Vehicles'), ('active_vehicles', 'Active Vehicles'), ('vehicles_on_trip', 'Vehicles on Trip'), ('vehicles_in_maintenance', 'Vehicles in Maintenance'), ('total_drivers', 'Total Drivers'), ('available_drivers', 'Available Drivers'), ('active_trips', 'Active Trips'), ('completed_trips', 'Completed Trips'), ('total_revenue', 'Total Revenue'), ('total_expenses', 'Total Expenses'), ('fuel_efficiency', 'Fuel Efficiency'), ('fleet_utilization', 'Fleet Utilization')], max_length=50, unique=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('trend', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard KPI',
                'verbose_name_plural': 'Dashboard KPIs',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('trip_summary', 'Trip Summary'), ('vehicle_performance', 'Vehicle Performance'), ('driver_performance', 'Driver Performance'), ('fuel_consumption', 'Fuel Consumption'), ('maintenance_summary', 'Maintenance Summary'), ('expense_report', 'Expense Report'), ('revenue_report', 'Revenue Report'), ('fleet_utilization', 'Fleet Utilization'), ('safety_report', 'Safety Report')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('data', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('is_generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('maintenance_due', 'Maintenance Due'), ('license_expiry', 'License Expiry'), ('insurance_expiry', 'Insurance Expiry'), ('registration_expiry', 'Registration Expiry'), ('fuel_budget_exceeded', 'Fuel Budget Exceeded'), ('vehicle_overdue', 'Vehicle Overdue'), ('safety_incident', 'Safety Incident'), ('low_fuel_efficiency', 'Low Fuel Efficiency'), ('expense_threshold', 'Expense Threshold')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('action_required', models.BooleanField(default=True)),
                ('action_taken', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='drivers.driver')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trips.trip')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('total_distance', 'Total Distance'), ('total_fuel_consumed', 'Total Fuel Consumed'), ('average_fuel_efficiency', 'Average Fuel Efficiency'), ('total_maintenance_cost', 'Total Maintenance Cost'), ('total_fuel_cost', 'Total Fuel Cost'), ('total_expenses', 'Total Expenses'), ('vehicle_utilization_rate', 'Vehicle Utilization Rate'), ('driver_utilization_rate', 'Driver Utilization Rate'), ('trip_completion_rate', 'Trip Completion Rate'), ('average_trip_duration', 'Average Trip Duration'), ('safety_score', 'Safety Score'), ('customer_satisfaction', 'Customer Satisfaction')], max_length=50)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='drivers.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-date'],
                'unique_together': {('metric_type', 'date', 'vehicle', 'driver')},
            },
        ),
    ]
