# Generated by Django 4.2.7 on 2026-02-21 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('hire_date', models.DateField()),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_type', models.CharField(max_length=50)),
                ('license_expiry', models.DateField()),
                ('status', models.CharField(choices=[('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('suspended', 'Suspended'), ('on_leave', 'On Leave')], default='off_duty', max_length=20)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DriverPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('completed_trips', models.PositiveIntegerField(default=0)),
                ('cancelled_trips', models.PositiveIntegerField(default=0)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fuel_consumed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('safety_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('on_time_performance', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('customer_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('last_trip_date', models.DateField(blank=True, null=True)),
                ('accidents_count', models.PositiveIntegerField(default=0)),
                ('violations_count', models.PositiveIntegerField(default=0)),
                ('bonus_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Driver Performance',
                'verbose_name_plural': 'Driver Performances',
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('license', 'Driving License'), ('medical', 'Medical Certificate'), ('background', 'Background Check'), ('training', 'Training Certificate'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='driver_documents/')),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Driver Document',
                'verbose_name_plural': 'Driver Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day')], default='present', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Driver Attendance',
                'verbose_name_plural': 'Driver Attendance',
                'ordering': ['-date'],
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
