# Generated by Django 4.2.7 on 2026-02-21 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, help_text='Vehicle chassis number', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, help_text='Vehicle color', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current market value', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, help_text='Engine serial number', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(blank=True, help_text='Engine specifications (e.g., 2.5L Turbo Diesel)', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel efficiency in km/l', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG'), ('lpg', 'LPG')], default='diesel', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, help_text='Vehicle manufacturer (e.g., Toyota, Ford, Mercedes)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT'), ('semi_automatic', 'Semi-Automatic')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Manufacturing year', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.DecimalField(decimal_places=2, help_text='Load capacity in kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
