# Generated by Django 4.2.7 on 2026-02-21 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_profile_picture'),
        ('vehicles', '0002_vehicle_chassis_number_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, help_text='Body type (e.g., Box Truck, Flatbed, Tanker)', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='curb_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Curb weight in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_location',
            field=models.CharField(blank=True, help_text='Current location of vehicle', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('2wd', '2WD'), ('4wd', '4WD'), ('awd', 'AWD')], help_text='Drive type', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fitness_expiry',
            field=models.DateField(blank=True, help_text='Fitness certificate expiry date', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gross_vehicle_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GVW in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='interior_color',
            field=models.CharField(blank=True, help_text='Interior color', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Loan amount if financed', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='loan_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Loan interest rate %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='loan_tenure_months',
            field=models.PositiveIntegerField(blank=True, help_text='Loan tenure in months', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='monthly_emi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly EMI amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='number_of_doors',
            field=models.PositiveIntegerField(blank=True, help_text='Number of doors', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='number_of_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Number of seats', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pollution_expiry',
            field=models.DateField(blank=True, help_text='Pollution certificate expiry date', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='road_tax_expiry',
            field=models.DateField(blank=True, help_text='Road tax expiry date', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='warranty_expiry',
            field=models.DateField(blank=True, help_text='Warranty expiry date', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wheelbase',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wheelbase in cm', max_digits=8, null=True),
        ),
    ]
